config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:show, :update, :edit]

  resources :budgets
  resources :projects

  root to: 'pages#home'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :project
end

app/models/budgetisation.rb
class Budgetisation < ApplicationRecord
  belongs_to :project
  belongs_to :budget
end

app/models/profile.rb
class Profile < ApplicationRecord

belongs_to :user

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  has_one :profile


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.require(:budget).permit(:amount, :project_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update]
  before_action :authenticate_user!


  def show
  end

  def new
    @profile = Profile.new
    
  end


  def edit
  end



  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Vous venez de modifier votre profil avec succès' }
    
      else
        format.html { render :edit }
        
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:description, :skills, :linkedin_url, :age, :city, :user_id, :sector_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :budget_id, :profile_needed, :files, :city, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: budget, local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.amount %></td>
        <td><%= budget.project %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @budget.amount %>
</p>

<p>
  <strong>Project:</strong>
  <%= @budget.project %>
</p>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="footer footer-default">
            <div class="container">
                <nav>
                    <ul>
                        <li>
                            <a href="">
                                Privacy policy
                            </a>
                        </li>
                        <li>
                            <a href="">
                                About Us
                            </a>
                        </li>
                        <li>
                            <a href="">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                  
                </div>
            </div>
        </footer>

app/views/layouts/_footer2.html.erb
<footer class="footer">
            <div class="container">
                <nav>
                    <ul>
                        <li>
                            <a href="#">
                                Privacy policy
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                About Us
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright">
                   
                   
                </div>
            </div>
  </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md bg-primary fixed-top navbar-transparent " color-on-scroll="400">
        <div class="container">
            <div class="dropdown button-dropdown">
                <a href="#" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
                    <span class="button-bar"></span>
                    <span class="button-bar"></span>
                    <span class="button-bar"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="./index.html">Profile</a>
                    <a class="dropdown-item" href="./friends-page.html">Find Partners -</a>
                    <a class="dropdown-item" href="./edit-profile.html">Edit profile</a>
                    <a class="dropdown-item" href="./messages-page.html">Messages</a>
                    <%= link_to 'Projects', projects_path, class: "dropdown-item" %>
                    <% if current_user %>
                        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    <% else %>
                        <%= link_to 'Sign up' ,  new_user_registration_path, class: "dropdown-item" %>
                        <%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
                    <% end %>
                    <a class="dropdown-item" href="./nucleo-icons.html">Articles</a>
                </div>
            </div>
            <div class="navbar-translate">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
                <a class="navbar-brand"  href="#">
                    Be-My-Partner
                </a>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="imgages/startup.jpg">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link"  href="./index.html">
                            <p class="hidden-lg-up">Profile</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./friends.html">
                            <p class="hidden-lg-up">Find friends</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./edit-profile.html">
                            <p class="hidden-lg-up">Edit profile</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./chat.html">
                            <p class="hidden-lg-up">Messages</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./components.html">
                            <p class="hidden-lg-up">Components</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./login-page.html">
                            <p class="hidden-lg-up">Login</p>
                        </a>
                        
                    </li>
                    <li class="nav-item">
                            <%= link_to 'Sign in', new_user_session_path, class: "hidden-lg-up" %>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./landing-page.html">
                            <p class="hidden-lg-up">Landing page</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./nucleo-icons.html">
                            <p class="hidden-lg-up">Icons</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeMyPartner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :compétences %>
    <%= form.text_field :skills %>
  </div>

  <div class="field">
    <%= form.label :linkedin %>
    <%= form.text_field :linkedin_url %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :ville %>
    <%= form.text_field :city %>
  </div>


  <div class="actions">
    <%= form.submit :Confirmer%>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Modifiez votre Profil</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Retourner au profil', @profile %> 

app/views/profiles/show.html.erb
<h1>Bienvenue sur votre profil public. </h1>

<p>
  <strong>Description:</strong>
  <%= @profile.description %>
</p>

<p>
  <strong>Compétences:</strong>
  <%= @profile.skills %>
</p>

<p>
  <strong>Lien Linkedin:</strong>
  <%= @profile.linkedin_url %>
</p>

<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @profile.city %>
</p>



<%= link_to 'Modifiez votre profil', edit_profile_path(@profile) %> 

app/views/projects/_form.html.erb
<main class="container-section">
<article> 
    <div class="wrapper">
        <section class="container-section-banner">
            <div class="page-header page-header-small">
                <div class="page-header-image" data-parallax="true" style="background-image: url('/assets/startup.jpg');"></div>
                <h1>Edit project</h1>
            </div>
        </section> 
    </div>
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="porfile-content">
                        <div class="photo-container img-edit-profile">
                            <img src="img/Friends/guy-3.jpg" alt="">
                        </div>
                        <label for="photoFile" class="btn btn-primary ">Files</label>
                        <input type="file" class="hidden-xl-down" id="photoFile">
                    </div>
                </div>
                <div class="col-12">
                  <%= form_with(model: project, local: true, class: "edit-porfile") do |form| %>
                        <div class="form-group row">
                            <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                <label for="Name" class="p2">Title</label>
                                <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
                                <span class="error"></span>
                            </div>
                            <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                <label for="LastName" class="p2">Budget</label>
                                <%= form.number_field :budget_id, class: "form-control", placeholder: "Budget" %>
                                <span class="error"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                <label for="Name" class="p2">City</label>
                                <%= form.text_field :city, class: "form-control", placeholder: "City" %>
                                <span class="error"></span>
                            </div>
                            <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
                                <label for="LastName" class="p2">Profil needed</label>
                                <%= form.text_field :profile_needed, class: "form-control", placeholder: "Required profile" %>
                                <span class="error"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                <label for="Email" class="p2">Files</label>
                                <%= form.text_field :files, class: "form-control", placeholder: "Files" %>
                                <span class="error"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                <label for="Descropcion" class="p2">Description</label>
                                <%= form.text_area :description, placeholder: "Tell to your futur partner about your project", class: "form-control", cols: "30", rows: "3" %>
                                <span class="error"></span>
                            </div>
                        </div>
                        
                        <%= form.submit class: "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</article>
</main>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<main class="container-section">
<%= render ("layouts/header") %>
    <div class="wrapper">
        <section class="container-section-banner">
            <div class="page-header page-header-small">
                <div class="page-header-image" data-parallax="true" style="background-image: url('/assets/startup2.jpg');"></div>
                <h1>Your Projects</h1>
            </div>
        </section>
    </div>
    <div class="porfile-content">
      <h6><%= link_to 'New Project', new_project_path, class: "link"%></h6>
      <h6><%= link_to 'Home', root_path, class: "link" %></h6> 
    </div>
  <div class="tab-pane Followers" id="followers" role="tabpanel">
    <div class="container-fluid">
        <div class="row">
        <% @projects.each do |project| %>
          <div class="col-12 col-sm-6">
           <div class="card">
              <img class="card-img-top" src="/assets/workplace.jpg" alt="Card image cap">
              <div class="card-block">
                  <img class="img-profile-folow" src="img/Friends/woman-1.jpg" alt="">
                    <h4><strong> <%= project.title %></strong> </h4>
                    </br>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Budget :</strong>  <%= project.budget_id %></li>
                <li class="list-group-item"><strong>City :</strong>  <%= project.city %></li>
                <li class="list-group-item"><strong>Profile needed :</strong>   <%= project.profile_needed %></li>
                <li class="list-group-item"><strong>Files :</strong> <%= project.profile_needed %></li>
                <li class="list-group-item"><strong>Contact of the project owner :</strong>  <%= project.user.email %></li>
              </ul>
                    </br>
        <p class="card-text"><strong> Project description:</strong>  <%= project.description %></p>

        <div class="card-body">
          <%= link_to 'Show', project, class: "card-link" %>
          <%= link_to 'Edit', edit_project_path(project), class: "card-link" %>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link" %>
        </div>
        
        </div>
      </div>
  </div>
          <% end %>
        </div>
    </div>
  </div>
  <%= render ("layouts/footer") %>
</main>

app/views/projects/new.html.erb
<%= render "layouts/header" %>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

<%= render("layouts/footer") %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @project.budget_id %>
</p>

<p>
  <strong>Profile needed:</strong>
  <%= @project.profile_needed %>
</p>

<p>
  <strong>Files:</strong>
  <%= @project.files %>
</p>

<p>
  <strong>City:</strong>
  <%= @project.city %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user.email %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>